const Jokes = [
    {joke: "Why do dogs love to hang out of car windows?", punchline: "Because they're HOT dogs."},
    {joke: "Why was the grape mad at his Dad?", punchline: "Because he wasn't there when he needed raisin."},
    {joke: "What do you call a lover who snoops through your phone?", punchline: "A peek-a-boo."},
    {joke: "What did the bartender say to the jumper cables?", punchline: "You better not try to start anything."},
    {joke: "What did Santa Clause say to Ms. Clause when he caught her cheating?", punchline: "You ho, ho, ho."},
    {joke: "Don't you hate jokes about German sausage?", punchline: "They're the wurst!"},
    {joke: "Two artists had an art contest...", punchline: "It ended in a draw."},
    {joke: "What do you call a cloud with long nails?", punchline: "A sky scraper."},
    {joke: "What did the hitchhiker say to the Uber driver?", punchline: "Can I get a Lyft?"},
    {joke: "Why did the chicken cross the playground?", punchline: "To get to the other slide."},
    {joke: "How do rappers clean up their mess?", punchline: "With 'Lil Baby' wipes."},
    {joke: "Broken pencils...", punchline: "...are pointless."},
    {joke: "Old Chinese proverb:", punchline: "Man who not shower in 7 days makes one reek."},
    {joke: "What form of radiation bakes you cookies?", punchline: "A gramma ray"},
    {joke: "What did the owner of a brownie factory say when his factory caught fire?", punchline: "I'm getting the fudge outta here!"},
    {joke: "What's the loudest economic system?", punchline: "CAPITALISM"},
    {joke: "What's worse than a centipede with sore feet?", punchline: "A giraffe with a sore throat."},
    {joke: "What's red and bad for your teeth?", punchline: "A brick."},
    {joke: "Wanna hear a joke about unemployed people?", punchline: "Nevermind, they don't work."},
    {joke: "What did the corn say when it was complemented?", punchline: "Aww, shucks!"},
    {joke: "If I ever fire someone who is a Taylor Swift fan I'll say:", punchline: "'I knew you were trouble when you clocked in.'"},
    {joke: "What's a dog's favorite mode of transportation?", punchline: "A waggin'"},
    {joke: "What did earth say to the other planets?", punchline: "You guys have no life!"},
    {joke: "What do you call a pig that does karate? ", punchline: "*A pork chop.*"},
    {joke: "Why did the bicycle fall over?", punchline: "Because it was two-tired."},
    {joke: "What did the fish say when it hit the wall?", punchline: "Dam."},
    {joke: "What's that coffee drink with icecream?", punchline: "I used to know it, but... Affogato."},
    {joke: "Can February March?", punchline: "No, but April May."},
];

export default Jokes;